// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgW2H-Ws0UYVZIQldROqrr3-A9LbfEUX8',
    appId: '1:407650103857:web:b53464018077c16168db10',
    messagingSenderId: '407650103857',
    projectId: 'rifugi-e-bivacchi-4ed0b',
    authDomain: 'rifugi-e-bivacchi-4ed0b.firebaseapp.com',
    storageBucket: 'rifugi-e-bivacchi-4ed0b.firebasestorage.app',
    measurementId: 'G-BVKFNH6N70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYKjpuiUl1SIrkgpw7KLCBeLZD56NASog',
    appId: '1:407650103857:android:001741b2fedb76c668db10',
    messagingSenderId: '407650103857',
    projectId: 'rifugi-e-bivacchi-4ed0b',
    storageBucket: 'rifugi-e-bivacchi-4ed0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2WDej30ee3QiD2Zv04ehzZbrKXJ_Axgo',
    appId: '1:407650103857:ios:dc1e27e5f6996bc568db10',
    messagingSenderId: '407650103857',
    projectId: 'rifugi-e-bivacchi-4ed0b',
    storageBucket: 'rifugi-e-bivacchi-4ed0b.firebasestorage.app',
    androidClientId: '407650103857-dvuo09ungo5plmeltq5q7p1pb61rcp8m.apps.googleusercontent.com',
    iosClientId: '407650103857-160lar1n257fhet49ujah147bqfddtl7.apps.googleusercontent.com',
    iosBundleId: 'it.federicooldrini.rifugiebivacchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2WDej30ee3QiD2Zv04ehzZbrKXJ_Axgo',
    appId: '1:407650103857:ios:dc1e27e5f6996bc568db10',
    messagingSenderId: '407650103857',
    projectId: 'rifugi-e-bivacchi-4ed0b',
    storageBucket: 'rifugi-e-bivacchi-4ed0b.firebasestorage.app',
    androidClientId: '407650103857-dvuo09ungo5plmeltq5q7p1pb61rcp8m.apps.googleusercontent.com',
    iosClientId: '407650103857-160lar1n257fhet49ujah147bqfddtl7.apps.googleusercontent.com',
    iosBundleId: 'it.federicooldrini.rifugiebivacchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgW2H-Ws0UYVZIQldROqrr3-A9LbfEUX8',
    appId: '1:407650103857:web:fe42f992bcb8f4c368db10',
    messagingSenderId: '407650103857',
    projectId: 'rifugi-e-bivacchi-4ed0b',
    authDomain: 'rifugi-e-bivacchi-4ed0b.firebaseapp.com',
    storageBucket: 'rifugi-e-bivacchi-4ed0b.firebasestorage.app',
    measurementId: 'G-VVMTGPG01J',
  );

}